// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190717a), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/movement/swiss_system_ensuing_matchday_generator/MatchdayGeneratorSwissSystem.lfet"
// 13.02.2020 22:41
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (190717a) build in default

package org.dos.tournament.branch.petanque.tournament.movement.swisssystem;

public final class SwissMatchdayGeneratorRulesEngine
{
    public final void execute(ISwissMatchdayGeneration iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$InterfaceName=ISwissMatchdayGeneration        
        // $$InterfaceRulesClassName=SwissMatchdayGeneratorRulesEngine        
        // $$package=org.dos.tournament.branch.petanque.tournament.movement.swisssystem        
        //         
        // $$InterfaceRuleGroups=true     
        // $$InterfaceRuleMethods=false
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
        
            if ( ruleGroup == 1 )
            {
                // Rule R01 ---->
                
                iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 1);
                iface.doReadActiveTeams();
                iface.doReadAvailableTerrains();
                iface.doCreatePots();
                
                ruleGroup = 2;
                exit = false;
                
                // Rule R01 <----
            }
            else if ( ruleGroup == 2 )
            {
                if ( iface.hasNextTeam() )
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 2);
                    iface.doSetTeamToFirstPot();
                    iface.doResetCounterMatchday();
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R02 <----
                }
                else
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 3);
                    iface.doInitCounterPot();
                    
                    ruleGroup = 4;
                    exit = false;
                    
                    // Rule R03 <----
                }
            }
            else if ( ruleGroup == 3 )
            {
                if ( iface.isMatchdayCounterBehindLast() )
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 4);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R04 <----
                }
                else
                {
                    if ( iface.isTeamWinner() )
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 5);
                        iface.doPromoteTeamToNextPot();
                        iface.doIncreaseCounterMatchday();
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else
                    {
                        // Rule R06 ---->
                        
                        iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 6);
                        iface.doIncreaseCounterMatchday();
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R06 <----
                    }
                }
            }
            else
            {
                if ( iface.isPotEmpty() )
                {
                    if ( iface.isCounterInLastPot() )
                    {
                        // Rule R07 ---->
                        
                        iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 7);
                        
                        exit = true;
                        
                        // Rule R07 <----
                    }
                    else
                    {
                        // Rule R08 ---->
                        
                        iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 8);
                        iface.doDecreaseCounterPot();
                        
                        ruleGroup = 4;
                        exit = false;
                        
                        // Rule R08 <----
                    }
                }
                else if ( iface.isOneTeamLeftInPot() )
                {
                    if ( iface.isCounterInLastPot() )
                    {
                        // Rule R09 ---->
                        
                        iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 9);
                        iface.doDrawHomeFromPot();
                        iface.doSetGuestBye();
                        iface.doCreatePartie();
                        
                        exit = true;
                        
                        // Rule R09 <----
                    }
                    else
                    {
                        // Rule R10 ---->
                        
                        iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 10);
                        iface.doDrawHomeFromPot();
                        iface.doDrawGuestPromotedFromPot();
                        iface.doCreatePartie();
                        
                        ruleGroup = 4;
                        exit = false;
                        
                        // Rule R10 <----
                    }
                }
                else
                {
                    // Rule R11 ---->
                    
                    iface.doTrace("MatchdayGeneratorSwissSystem", "20200213.224135", 11, 11);
                    iface.doDrawHomeFromPot();
                    iface.doDrawGuestFromPot();
                    iface.doCreatePartie();
                    
                    ruleGroup = 4;
                    exit = false;
                    
                    // Rule R11 <----
                }
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190717a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190717a), http://www.lohrfink.de/lfet

