// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190129a), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/factory-create_tournament.lfet"
// 30.01.2019 13:42
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.1.5 (190129a) build in default

package org.dos.tournament.application.factory.model;

public interface ITournamentWorker
{
 
    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$InterfaceName=ITournamentWorker
    // $$InterfaceRulesClassName=TournamentFactoryRulesEngine
    // $$package=org.dos.tournament.application.factory.model
    // 
    // $$InterfaceRuleGroups=true
    // Prolog Decision Table <----
    
    /** 
     * <b>B02: branch</b><br>
     * <br>
     * <b>B02/01: petanque - Boule-Turnier soll angelegt werden</b>
     */
    public boolean isBranch_Petanque();
    
    /** 
     * <b>B03: ruleInStack</b>
     */
    public boolean isRuleInStack();
    
    /** 
     * <b>A01: createMovement</b>
     */
    public void doCreateMovement();
    
    /** 
     * <b>A02: addRule</b>
     */
    public void doAddRule();
    
    /** 
     * <b>A03: createGUI</b>
     */
    public void doCreateGUI();
    
    /** 
     * <b>A04: createErrorMessage</b>
     */
    public void doCreateErrorMessage();
    
    public void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule);

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.1.5 (190129a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190129a), http://www.lohrfink.de/lfet

