// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190717a), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/wizards/create_tournament/factory-create_tournament.lfet"
// 13.02.2020 22:41
// 
// Prolog Standard ---->
// code used from profile: 
// C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/wizards/create_tournament/LFET.Java.Prolog.Standard.Interface.ini (05.06.2019 20:43, 195 bytes)
package org.dos.tournament.application.factory.model;

import org.dos.tournament.application.common.wizard.common.IWizardWorker;

public interface ITournamentWorker extends IWizardWorker
{
    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$InterfaceName=ITournamentWorker        
    // $$InterfaceRulesClassName=TournamentFactoryRulesEngine        
    // $$package=org.dos.tournament.application.factory.model        
    //         
    // $$InterfaceRuleGroups=true     
    // $$InterfaceRuleMethods=false
    // Prolog Decision Table <----
    
    /** 
     * <b>B02: properties: branch</b><br>
     * <br>
     * <b>B02/01: null - keine Vorauswahl</b>
     */
    public boolean isPropertiesBranch_Null();
    
    /** 
     * <b>B02: properties: branch</b><br>
     * <br>
     * <b>B02/02: petanque - Petanque-Turnier</b>
     */
    public boolean isPropertiesBranch_Petanque();
    
    /** 
     * <b>B03: wizard control: wizard visible</b>
     */
    public boolean isWizardControlWizardVisible();
    
    /** 
     * <b>B04: wizard control: empty pane</b>
     */
    public boolean isWizardControlEmptyPane();
    
    /** 
     * <b>B05: wizard control: command</b><br>
     * <br>
     * <b>B05/01: cancel - Abbrechen der Erstellung</b>
     */
    public boolean isWizardControlCommand_Cancel();
    
    /** 
     * <b>B05: wizard control: command</b><br>
     * <br>
     * <b>B05/02: back - zurück zum vorherigen Schritt</b>
     */
    public boolean isWizardControlCommand_Back();
    
    /** 
     * <b>B05: wizard control: command</b><br>
     * <br>
     * <b>B05/03: next - weiter zum nächsten Schritt</b>
     */
    public boolean isWizardControlCommand_Next();
    
    /** 
     * <b>B06: wizard: branch</b><br>
     * <br>
     * <b>B06/01: null - keine Vorauswahl</b>
     */
    public boolean isWizardBranch_Null();
    
    /** 
     * <b>B06: wizard: branch</b><br>
     * <br>
     * <b>B06/02: petanque - Petanque-Turnier</b>
     */
    public boolean isWizardBranch_Petanque();
    
    /** 
     * <b>B07: wizard: last step</b><br>
     * <br>
     * <b>B07/01: branch - Auswahl der Turnierart</b>
     */
    public boolean isWizardLastStep_Branch();
    
    /** 
     * <b>B07: wizard: last step</b><br>
     * <br>
     * <b>B07/02: pet-cat - Petanque: Auswahl der Turnierform</b>
     */
    public boolean isWizardLastStep_PetCat();
    
    /** 
     * <b>B07: wizard: last step</b><br>
     * <br>
     * <b>B07/03: pet-sup-sel - Petanque - Supermelee: Regeln zur Auslosung</b>
     */
    public boolean isWizardLastStep_PetSupSel();
    
    /** 
     * <b>B08: pet-cat: tournament category</b><br>
     * <br>
     * <b>B08/01: null - keine Auswahl getroffen</b>
     */
    public boolean isPetCatTournamentCategory_Null();
    
    /** 
     * <b>B08: pet-cat: tournament category</b><br>
     * <br>
     * <b>B08/02: supermelee - Allgemeines Supermelee</b>
     */
    public boolean isPetCatTournamentCategory_Supermelee();
    
    /** 
     * <b>B08: pet-cat: tournament category</b><br>
     * <br>
     * <b>B08/03: sup-monat - Monatsturnier nach Regeln von Groß-Gerau</b>
     */
    public boolean isPetCatTournamentCategory_SupMonat();
    
    /** 
     * <b>B09: pet-com-mov: time boxed</b>
     */
    public boolean isPetComMovTimeBoxed();
    
    /** 
     * <b>B10: pet-com-mov: time limit defined</b><br>
     * <br>
     * <b>B10/01: J - Ja</b>
     */
    public boolean isPetComMovTimeLimitDefined_J();
    
    /** 
     * <b>B11: pet-com-mov: define tracks by movement</b>
     */
    public boolean isPetComMovDefineTracksByMovement();
    
    /** 
     * <b>A01: dispose selected branch from properties</b>
     */
    public void doDisposeSelectedBranchFromProperties();
    
    /** 
     * <b>A02: petanque: time boxed matchday</b>
     */
    public void doPetanqueTimeBoxedMatchday();
    
    /** 
     * <b>A03: petanque: define tracks by movement</b>
     */
    public void doPetanqueDefineTracksByMovement();
    
    /** 
     * <b>A04: petanque: create tournament instance</b><br>
     * <br>
     * <b>A04/01: supermelee - Allgemeines Supermelee</b>
     */
    public void doPetanqueCreateTournamentInstance_Supermelee();
    
    /** 
     * <b>A04: petanque: create tournament instance</b><br>
     * <br>
     * <b>A04/02: sup-monat - Monatsturnier nach Regeln von Groß-Gerau</b>
     */
    public void doPetanqueCreateTournamentInstance_SupMonat();
    
    /** 
     * <b>A05: petanque: delete tournament instance</b>
     */
    public void doPetanqueDeleteTournamentInstance();
    
    /** 
     * <b>A06: wizard control: status cancel</b><br>
     * <br>
     * <b>A06/01: enabled - aktiviert</b>
     */
    public void doWizardControlStatusCancel_Enabled();
    
    /** 
     * <b>A06: wizard control: status cancel</b><br>
     * <br>
     * <b>A06/02: disabled - deaktiviert</b>
     */
    public void doWizardControlStatusCancel_Disabled();
    
    /** 
     * <b>A07: wizard control: status back</b><br>
     * <br>
     * <b>A07/01: enabled - aktiviert</b>
     */
    public void doWizardControlStatusBack_Enabled();
    
    /** 
     * <b>A07: wizard control: status back</b><br>
     * <br>
     * <b>A07/02: disabled - deaktiviert</b>
     */
    public void doWizardControlStatusBack_Disabled();
    
    /** 
     * <b>A08: wizard control: status next</b><br>
     * <br>
     * <b>A08/01: enabled - aktiviert</b>
     */
    public void doWizardControlStatusNext_Enabled();
    
    /** 
     * <b>A08: wizard control: status next</b><br>
     * <br>
     * <b>A08/02: disabled - deaktiviert</b>
     */
    public void doWizardControlStatusNext_Disabled();
    
    /** 
     * <b>A08: wizard control: status next</b><br>
     * <br>
     * <b>A08/03: to_finish - aktiviert und Beschriftung wechselt</b>
     */
    public void doWizardControlStatusNext_To_Finish();
    
    /** 
     * <b>A09: wizard control: set panel</b><br>
     * <br>
     * <b>A09/01: dispose - aktuelles Panel löschen</b>
     */
    public void doWizardControlSetPanel_Dispose();
    
    /** 
     * <b>A09: wizard control: set panel</b><br>
     * <br>
     * <b>A09/02: branch - Panel zur Auswahl der Turnierart</b>
     */
    public void doWizardControlSetPanel_Branch();
    
    /** 
     * <b>A09: wizard control: set panel</b><br>
     * <br>
     * <b>A09/03: pet-cat - Petanque: Panel zur Auswahl der Turnierform</b>
     */
    public void doWizardControlSetPanel_PetCat();
    
    /** 
     * <b>A09: wizard control: set panel</b><br>
     * <br>
     * <b>A09/04: pet-sup-sel - Petanque - Supermelee: Regeln zur Auslosung</b>
     */
    public void doWizardControlSetPanel_PetSupSel();
    
    /** 
     * <b>A09: wizard control: set panel</b><br>
     * <br>
     * <b>A09/05: pet-com-mov - Petanque: Allgemeine Regeln zum Ablauf einer Runde</b>
     */
    public void doWizardControlSetPanel_PetComMov();
    
    /** 
     * <b>A10: wizard control: roll-back</b><br>
     * <br>
     * <b>A10/01: dispose - aktuelles Panel löschen</b>
     */
    public void doWizardControlRollBack_Dispose();
    
    /** 
     * <b>A10: wizard control: roll-back</b><br>
     * <br>
     * <b>A10/02: branch - Panel zur Auswahl der Turnierart</b>
     */
    public void doWizardControlRollBack_Branch();
    
    /** 
     * <b>A10: wizard control: roll-back</b><br>
     * <br>
     * <b>A10/03: pet-cat - Petanque: Panel zur Auswahl der Turnierform</b>
     */
    public void doWizardControlRollBack_PetCat();
    
    /** 
     * <b>A10: wizard control: roll-back</b><br>
     * <br>
     * <b>A10/04: pet-sup-sel - Petanque - Supermelee: Regeln zur Auslosung</b>
     */
    public void doWizardControlRollBack_PetSupSel();
    
    /** 
     * <b>A10: wizard control: roll-back</b><br>
     * <br>
     * <b>A10/05: pet-com-mov - Petanque: Allgemeine Regeln zum Ablauf einer Runde</b>
     */
    public void doWizardControlRollBack_PetComMov();
    
    /** 
     * <b>A11: wizard control: pause</b>
     */
    public void doWizardControlPause();
    
    /** 
     * <b>A12: display hint</b><br>
     * <br>
     * <b>A12/01: select - Hinweis: Wählen Sie eine Turnierart aus</b>
     */
    public void doDisplayHint_Select();
    
    /** 
     * <b>A13: dispose product</b>
     */
    public void doDisposeProduct();
    
    /** 
     * <b>A14: deliver product</b>
     */
    public void doDeliverProduct();
    
    public void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule);

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.1.5 (190717a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190717a), http://www.lohrfink.de/lfet

