// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190129a), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/factory-create_tournament.lfet"
// 30.01.2019 13:42
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (190129a) build in default

package org.dos.tournament.application.factory.model;

public final class TournamentFactoryRulesEngine
{
    public final void execute(ITournamentWorker iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$InterfaceName=ITournamentWorker
        // $$InterfaceRulesClassName=TournamentFactoryRulesEngine
        // $$package=org.dos.tournament.application.factory.model
        // 
        // $$InterfaceRuleGroups=true
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
        
            if ( ruleGroup == 1 )
            {
                if ( iface.isBranch_Petanque() )
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("factory-create_tournament", "20190130.134252", 6, 1);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("factory-create_tournament", "20190130.134252", 6, 2);
                    iface.doCreateErrorMessage();
                    
                    exit = true;
                    
                    // Rule R02 <----
                }
            }
            else if ( ruleGroup == 2 )
            {
                // Rule R03 ---->
                
                iface.doTrace("factory-create_tournament", "20190130.134252", 6, 3);
                iface.doCreateMovement();
                
                ruleGroup = 3;
                exit = false;
                
                // Rule R03 <----
            }
            else if ( ruleGroup == 3 )
            {
                if ( iface.isRuleInStack() )
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("factory-create_tournament", "20190130.134252", 6, 4);
                    iface.doAddRule();
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R04 <----
                }
                else
                {
                    // Rule R05 ---->
                    
                    iface.doTrace("factory-create_tournament", "20190130.134252", 6, 5);
                    
                    ruleGroup = 4;
                    exit = false;
                    
                    // Rule R05 <----
                }
            }
            else
            {
                // Rule R06 ---->
                
                iface.doTrace("factory-create_tournament", "20190130.134252", 6, 6);
                iface.doCreateGUI();
                
                exit = true;
                
                // Rule R06 <----
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190129a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190129a), http://www.lohrfink.de/lfet

