// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190626a), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/wizards/create_tournament/factory-create_tournament.lfet"
// 30.06.2019 10:02
// 

// Prolog Standard ---->
// code used from profile: 
// C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/wizards/create_tournament/LFET.Java.Prolog.Standard.Interface.Dt.ini (09.06.2019 16:04, 503 bytes)
package org.dos.tournament.application.factory.model;

import org.dos.tournament.application.common.wizard.common.AbstractWizardRuleEngine;
import org.dos.tournament.application.common.wizard.common.IWizardWorker;

public final class TournamentFactoryRulesEngine extends AbstractWizardRuleEngine
{
  
    @Override
    public void execute(IWizardWorker instance) 
    {
      this.execute((ITournamentWorker)instance);
    }

    public final void execute(ITournamentWorker iface)
    {
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$InterfaceName=ITournamentWorker   
        // $$InterfaceRulesClassName=TournamentFactoryRulesEngine   
        // $$package=org.dos.tournament.application.factory.model   
        //    
        // $$InterfaceRuleGroups=true
        // $$InterfaceRuleMethods=true
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
        
            if ( iface.isWizardControlWizardVisible() )
            {
                if ( ruleGroup == 1 )
                {
                    if ( iface.isPropertiesBranch_Null() )
                    {
                        if ( iface.isWizardControlEmptyPane() )
                        {
                            // Rule R02 ---->
                            
                            iface.doTrace("factory-create_tournament", "20190630.100223", 36, 2);
                            iface.doWizardControlStatusCancel_Enabled();
                            iface.doWizardControlStatusBack_Disabled();
                            iface.doWizardControlStatusNext_Disabled();
                            iface.doWizardControlSetPanel_Branch();
                            
                            ruleGroup = 1;
                            exit = false;
                            
                            // Rule R02 <----
                        }
                        else
                        {
                            if ( iface.isWizardControlCommand_Cancel() )
                            {
                                // Rule R03 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 3);
                                iface.doDisposeProduct();
                                
                                exit = true;
                                
                                // Rule R03 <----
                            }
                            else if ( iface.isWizardControlCommand_Back() )
                            {
                                // Rule R04 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 4);
                                
                                ruleGroup = 1;
                                exit = false;
                                
                                // Rule R04 <----
                            }
                            else if ( iface.isWizardControlCommand_Next() )
                            {
                                if ( iface.isWizardBranch_Null() )
                                {
                                    // Rule R05 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 5);
                                    iface.doDisplayHint_Select();
                                    
                                    ruleGroup = 1;
                                    exit = false;
                                    
                                    // Rule R05 <----
                                }
                                else if ( iface.isWizardBranch_Petanque() )
                                {
                                    // Rule R06 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 6);
                                    iface.doWizardControlSetPanel_Dispose();
                                    
                                    ruleGroup = 2;
                                    exit = false;
                                    
                                    // Rule R06 <----
                                }
                                else
                                {
                                    // Rule R07 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 7);
                                    iface.doWizardControlPause();
                                    
                                    ruleGroup = 1;
                                    exit = false;
                                    
                                    // Rule R07 <----
                                }
                            }
                            else
                            {
                                if ( iface.isWizardBranch_Null() )
                                {
                                    // Rule R08 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 8);
                                    iface.doWizardControlPause();
                                    
                                    ruleGroup = 1;
                                    exit = false;
                                    
                                    // Rule R08 <----
                                }
                                else if ( iface.isWizardBranch_Petanque() )
                                {
                                    // Rule R09 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 9);
                                    iface.doWizardControlStatusNext_Enabled();
                                    iface.doWizardControlPause();
                                    
                                    ruleGroup = 1;
                                    exit = false;
                                    
                                    // Rule R09 <----
                                }
                                else
                                {
                                    // Rule R10 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 10);
                                    iface.doWizardControlStatusNext_Disabled();
                                    iface.doWizardControlPause();
                                    
                                    ruleGroup = 1;
                                    exit = false;
                                    
                                    // Rule R10 <----
                                }
                            }
                        }
                    }
                    else if ( iface.isPropertiesBranch_Petanque() )
                    {
                        // Rule R11 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 11);
                        iface.doWizardControlSetPanel_Dispose();
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R11 <----
                    }
                    else
                    {
                        // Rule R12 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 12);
                        iface.doDisposeSelectedBranchFromProperties();
                        iface.doWizardControlStatusCancel_Enabled();
                        iface.doWizardControlStatusBack_Disabled();
                        iface.doWizardControlStatusNext_Disabled();
                        
                        ruleGroup = 1;
                        exit = false;
                        
                        // Rule R12 <----
                    }
                }
                else if ( ruleGroup == 2 )
                {
                    if ( iface.isWizardControlEmptyPane() )
                    {
                        // Rule R13 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 13);
                        iface.doWizardControlStatusCancel_Enabled();
                        iface.doWizardControlStatusBack_Enabled();
                        iface.doWizardControlStatusNext_Disabled();
                        iface.doWizardControlSetPanel_PetCat();
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R13 <----
                    }
                    else
                    {
                        if ( iface.isWizardControlCommand_Cancel() )
                        {
                            // Rule R14 ---->
                            
                            iface.doTrace("factory-create_tournament", "20190630.100223", 36, 14);
                            iface.doDisposeProduct();
                            
                            exit = true;
                            
                            // Rule R14 <----
                        }
                        else if ( iface.isWizardControlCommand_Back() )
                        {
                            // Rule R15 ---->
                            
                            iface.doTrace("factory-create_tournament", "20190630.100223", 36, 15);
                            iface.doWizardControlSetPanel_Dispose();
                            iface.doWizardControlRollBack_PetCat();
                            
                            ruleGroup = 1;
                            exit = false;
                            
                            // Rule R15 <----
                        }
                        else if ( iface.isWizardControlCommand_Next() )
                        {
                            if ( iface.isPetCatTournamentCategory_Null() )
                            {
                                // Rule R16 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 16);
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R16 <----
                            }
                            else if ( iface.isPetCatTournamentCategory_Supermelee() )
                            {
                                // Rule R17 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 17);
                                iface.doWizardControlSetPanel_Dispose();
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R17 <----
                            }
                            else if ( iface.isPetCatTournamentCategory_SupMonat() )
                            {
                                // Rule R18 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 18);
                                iface.doWizardControlSetPanel_Dispose();
                                
                                ruleGroup = 4;
                                exit = false;
                                
                                // Rule R18 <----
                            }
                            else
                            {
                                // Rule R19 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 19);
                                iface.doWizardControlStatusNext_Disabled();
                                iface.doWizardControlPause();
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R19 <----
                            }
                        }
                        else
                        {
                            if ( iface.isPetCatTournamentCategory_Null() )
                            {
                                // Rule R20 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 20);
                                iface.doWizardControlStatusNext_Disabled();
                                iface.doWizardControlPause();
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R20 <----
                            }
                            else if ( iface.isPetCatTournamentCategory_Supermelee() )
                            {
                                // Rule R21 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 21);
                                iface.doWizardControlStatusNext_Enabled();
                                iface.doWizardControlPause();
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R21 <----
                            }
                            else if ( iface.isPetCatTournamentCategory_SupMonat() )
                            {
                                // Rule R22 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 22);
                                iface.doWizardControlStatusNext_Enabled();
                                iface.doWizardControlPause();
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R22 <----
                            }
                            else
                            {
                                // Rule R23 ---->
                                
                                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 23);
                                iface.doWizardControlStatusNext_Disabled();
                                iface.doWizardControlPause();
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R23 <----
                            }
                        }
                    }
                }
                else if ( ruleGroup == 3 )
                {
                    // Rule R24 ---->
                    
                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 24);
                    iface.doDisposeProduct();
                    
                    exit = true;
                    
                    // Rule R24 <----
                }
                else if ( ruleGroup == 4 )
                {
                    if ( iface.isWizardControlEmptyPane() )
                    {
                        // Rule R25 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 25);
                        iface.doWizardControlStatusCancel_Enabled();
                        iface.doWizardControlStatusBack_Enabled();
                        iface.doWizardControlStatusNext_To_Finish();
                        iface.doWizardControlSetPanel_PetComMov();
                        
                        ruleGroup = 4;
                        exit = false;
                        
                        // Rule R25 <----
                    }
                    else
                    {
                        if ( iface.isWizardControlCommand_Cancel() )
                        {
                            // Rule R26 ---->
                            
                            iface.doTrace("factory-create_tournament", "20190630.100223", 36, 26);
                            iface.doDisposeProduct();
                            
                            exit = true;
                            
                            // Rule R26 <----
                        }
                        else if ( iface.isWizardControlCommand_Back() )
                        {
                            // Rule R27 ---->
                            
                            iface.doTrace("factory-create_tournament", "20190630.100223", 36, 27);
                            iface.doWizardControlSetPanel_Dispose();
                            iface.doWizardControlRollBack_PetComMov();
                            
                            ruleGroup = 5;
                            exit = false;
                            
                            // Rule R27 <----
                        }
                        else if ( iface.isWizardControlCommand_Next() )
                        {
                            if ( iface.isPetComMovTimeBoxed() )
                            {
                                if ( iface.isPetComMovDefineTracksByMovement() )
                                {
                                    // Rule R28 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 28);
                                    iface.doPetanqueTimeBoxedMatchday();
                                    iface.doPetanqueDefineTracksByMovement();
                                    iface.doDeliverProduct();
                                    
                                    exit = true;
                                    
                                    // Rule R28 <----
                                }
                                else
                                {
                                    // Rule R29 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 29);
                                    iface.doPetanqueTimeBoxedMatchday();
                                    iface.doDeliverProduct();
                                    
                                    exit = true;
                                    
                                    // Rule R29 <----
                                }
                            }
                            else
                            {
                                if ( iface.isPetComMovDefineTracksByMovement() )
                                {
                                    // Rule R30 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 30);
                                    iface.doPetanqueDefineTracksByMovement();
                                    iface.doDeliverProduct();
                                    
                                    exit = true;
                                    
                                    // Rule R30 <----
                                }
                                else
                                {
                                    // Rule R31 ---->
                                    
                                    iface.doTrace("factory-create_tournament", "20190630.100223", 36, 31);
                                    iface.doDeliverProduct();
                                    
                                    exit = true;
                                    
                                    // Rule R31 <----
                                }
                            }
                        }
                        else
                        {
                            // Rule R32 ---->
                            
                            iface.doTrace("factory-create_tournament", "20190630.100223", 36, 32);
                            
                            ruleGroup = 4;
                            exit = false;
                            
                            // Rule R32 <----
                        }
                    }
                }
                else
                {
                    if ( iface.isWizardLastStep_Branch() )
                    {
                        // Rule R33 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 33);
                        
                        ruleGroup = 1;
                        exit = false;
                        
                        // Rule R33 <----
                    }
                    else if ( iface.isWizardLastStep_PetCat() )
                    {
                        // Rule R34 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 34);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R34 <----
                    }
                    else if ( iface.isWizardLastStep_PetSupSel() )
                    {
                        // Rule R35 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 35);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R35 <----
                    }
                    else
                    {
                        // Rule R36 ---->
                        
                        iface.doTrace("factory-create_tournament", "20190630.100223", 36, 36);
                        
                        ruleGroup = 4;
                        exit = false;
                        
                        // Rule R36 <----
                    }
                }
            }
            else
            {
                // Rule R01 ---->
                
                iface.doTrace("factory-create_tournament", "20190630.100223", 36, 1);
                
                exit = true;
                
                // Rule R01 <----
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190626a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190626a), http://www.lohrfink.de/lfet

