// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190525x1), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/application-configuration.lfet"
// 30.05.2019 17:10
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (190525x1) build in default

package org.dos.tournament.application.configuration;

public final class ConfigurationEngine
{
    public final void execute(IConfigurableApplication iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$InterfaceName=IConfigurableApplication
        // $$InterfaceRulesClassName=ConfigurationEngine
        // $$interfaceRuleGroups=true
        // $$InterfacePrefixIs=_is
        // $$InterfacePrefixDo=_do
        // $$package=org.dos.tournament.application.configuration
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
        
            if ( ruleGroup == 1 )
            {
                if ( iface._isViewParameterExists() )
                {
                    if ( iface._isTournamentIDExists() )
                    {
                        // Rule R01 ---->
                        
                        iface._doTrace("application-configuration", "20190530.171053", 7, 1);
                        iface._doLoadTournament();
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R01 <----
                    }
                    else
                    {
                        // Rule R02 ---->
                        
                        iface._doTrace("application-configuration", "20190530.171053", 7, 2);
                        iface._doSelectTournament();
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R02 <----
                    }
                }
                else
                {
                    // Rule R03 ---->
                    
                    iface._doTrace("application-configuration", "20190530.171053", 7, 3);
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R03 <----
                }
            }
            else if ( ruleGroup == 2 )
            {
                if ( iface._isTournamentDataValid() )
                {
                    if ( iface._isOpenedInSateliteMode() )
                    {
                        // Rule R04 ---->
                        
                        iface._doTrace("application-configuration", "20190530.171053", 7, 4);
                        iface._doSetFileMenuVisible_False();
                        iface._doSetDefaultExitMode_HIDE();
                        
                        exit = true;
                        
                        // Rule R04 <----
                    }
                    else
                    {
                        // Rule R05 ---->
                        
                        iface._doTrace("application-configuration", "20190530.171053", 7, 5);
                        iface._doSetFileMenuVisible_False();
                        iface._doSetDefaultExitMode_EXIT();
                        
                        exit = true;
                        
                        // Rule R05 <----
                    }
                }
                else
                {
                    // Rule R06 ---->
                    
                    iface._doTrace("application-configuration", "20190530.171053", 7, 6);
                    iface._doDisplayErrorMessage();
                    iface._doCloseApplication();
                    
                    exit = true;
                    
                    // Rule R06 <----
                }
            }
            else
            {
                // Rule R07 ---->
                
                iface._doTrace("application-configuration", "20190530.171053", 7, 7);
                iface._doSetFileMenuVisible_True();
                
                exit = true;
                
                // Rule R07 <----
            }
        
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190525x1) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190525x1), http://www.lohrfink.de/lfet

