// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190416x1), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/application-configuration.lfet"
// 26.04.2019 05:58
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.1.5 (190416x1) build in default

package org.dos.tournament.application.configuration;

public interface IConfigurableApplication
{
 
    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$InterfaceName=IConfigurableApplication
    // $$InterfaceRulesClassName=ConfigurationEngine
    // $$interfaceRuleGroups=true
    // $$InterfacePrefixIs=_is
    // $$InterfacePrefixDo=_do
    // $$package=org.dos.tournament.application.configuration
    // Prolog Decision Table <----
    
    /** 
     * <b>B02: view parameter exists</b>
     */
    public boolean _isViewParameterExists();
    
    /** 
     * <b>B03: tournament ID exists</b>
     */
    public boolean _isTournamentIDExists();
    
    /** 
     * <b>B04: tournament data valid</b>
     */
    public boolean _isTournamentDataValid();
    
    /** 
     * <b>A01: load tournament</b>
     */
    public void _doLoadTournament();
    
    /** 
     * <b>A02: select tournament</b>
     */
    public void _doSelectTournament();
    
    /** 
     * <b>A03: set file menu visible</b><br>
     * <br>
     * <b>A03/01: true - menu visible</b>
     */
    public void _doSetFileMenuVisible_True();
    
    /** 
     * <b>A03: set file menu visible</b><br>
     * <br>
     * <b>A03/02: false - menu invisible</b>
     */
    public void _doSetFileMenuVisible_False();
    
    /** 
     * <b>A04: display error message</b>
     */
    public void _doDisplayErrorMessage();
    
    /** 
     * <b>A05: close application</b>
     */
    public void _doCloseApplication();
    
    public void _doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule);

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.1.5 (190416x1) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190416x1), http://www.lohrfink.de/lfet

