// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190717a), http://www.lohrfink.de/lfet
// From decision table
// "C:/Users/dirk.schweier/git/TournamentManager/src/lfet/tournament/movement/matchday_generator/MatchdayGeneration.lfet"
// 13.02.2020 22:41
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.1.5 (190717a) build in default

package org.dos.tournament.common.movement.utils;

public interface IMatchdayGenerator
{
 
    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$InterfaceName=IMatchdayGenerator         
    // $$InterfaceRulesClassName=MatchdayGeneratorEngine         
    // $$package=org.dos.tournament.common.movement.utils
    // Prolog Decision Table <----
    
    /** 
     * <b>B01: erster Spieltag/Runde im Turnier</b><br>
     * <br>
     * <b>B01/01: J - Ja</b><br>
     * <br>
     * <b>Java LogArg für B01/01: J</b><br>
     * <br>
     * $$MN=isFirstMatchday
     */
    public boolean isFirstMatchday();
    
    /** 
     * <b>B02: ist ein Finale definiert</b><br>
     * <br>
     * <b>Java LogArg für B02</b><br>
     * <br>
     * $$MN=isFinalsDefined
     */
    public boolean isFinalsDefined();
    
    /** 
     * <b>B03: wurden alle Spieltage/Runden vor der Finalrunge gespielt</b><br>
     * <br>
     * <b>Java LogArg für B03</b><br>
     * <br>
     * $$MN=isMatchdaysPlayed
     */
    public boolean isMatchdaysPlayed();
    
    /** 
     * <b>A01: erster Spieltag/Runde generieren</b><br>
     * <br>
     * <b>Java StmtSeq für A01</b><br>
     * <br>
     * $$MN=doGenerateFirstMatchday
     */
    public void doGenerateFirstMatchday();
    
    /** 
     * <b>A02: weiteren Spieltag/Runde generieren</b><br>
     * <br>
     * <b>Java StmtSeq für A02</b><br>
     * <br>
     * $$MN=doGenerateEnsuingMatchday
     */
    public void doGenerateEnsuingMatchday();
    
    /** 
     * <b>A03: Finalrunde generieren</b><br>
     * <br>
     * <b>Java StmtSeq für A03</b><br>
     * <br>
     * $$MN=doGenerateFinals
     */
    public void doGenerateFinals();
    
    public void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule);

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.1.5 (190717a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190717a), http://www.lohrfink.de/lfet

